---
name: Ansible Role Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    name: Lint Markdown
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Markdown via markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yaml

  lint-yaml:
    runs-on: ubuntu-latest
    name: Lint YAML
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint YAML via yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          config_file: ./.yamllint.yaml

  lint-shellcheck:
    runs-on: ubuntu-latest
    name: Lint Shell Scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint shell scripts via Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0

  lint-prettier:
    runs-on: ubuntu-latest
    name: Lint Code Formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint code formatting via Prettier
        uses: rutajdash/prettier-cli-action@v1.0.2
        with:
          config_path: .prettierrc.yaml

  lint-ansible:
    runs-on: ubuntu-latest
    name: Lint Ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Ansible
        uses: ansible/ansible-lint@v25
        with:
          args: ""
          setup_python: "true"
          python_version: "3.14"
          working_directory: "."
          requirements_file: "./.github/config/requirements.yaml"
